### ISSUE TITLE
autoread

### ISSUE THREAD

**Issue by boellner** [Supergiovane/KNXUltimate#2]
knx js library had object Datapoint which provides the autoread function. On startup all configured ga status are fetched by a groupvalue read. This is helpful for eg visualizations. 
Please add similar functionality.

**Comment by Supergiovane** [comment]
Hi
I cannot do that. The API doesn’t create GA objects. It works differently from the knxjs api. 
You should simply do it manually after the connection has been established.

**Comment by boellner** [comment]
sure, but isnt this a feature that most users of a library would need? I've seen it in other implementations and there is a reason why knxjs implemented it.

**Comment by Supergiovane** [comment]
Hi Franz
Nope. Knxjs works in it’s own way. KNXUltimate works differently. It’s up to you to create your own array containing the GA. Thanks to the “indication” event, you can get every single KNX telegram and change/update your array, even using powerful logic (for example, you can create an object containing the command GA and the status GA and handle in a more sophisticated way than knxjs.

**Comment by boellner** [comment]
Sorry that I dont understand what is working differently here that restricts having the feature. Is a common use case that after a device reset internal status intformations across devices are not in sync since knx is mostly sending trigger based. Visualisations do it, there's a read on init flag defined

**Comment by Supergiovane** [comment]
Look again at the readme and samples. I’ve implemented some changes. You should better understand how it works now.

**Comment by boellner** [comment]
Thank you for the example. But the question of this issue is not the acknowledgement, it is why KNXUltimate is not doing autoread. You worte it works differently but did not explain this design decision
