### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by erdemuncuoglu** [Supergiovane/KNXUltimate#20]
**Salutation**
Uncaught TypeError: Cannot read properties of undefined (reading '0')

**Describe the bug**
While trying to run example `sampleSecured.ts` I get error
`Uncaught TypeError: Cannot read properties of undefined (reading '0')`

**To Reproduce**
1. Run the `sampleSecured.ts` as is (I just changed KNX IP Router parameters)
2. See error:
```Uncaught TypeError: Cannot read properties of undefined (reading '0')
KNXSecureSessionRequest        	KNXSecu…SessionRequest.js:18
newKNXSecureSessionRequest     	KNXProtocol.js:102
sendSecureSessionRequestMessage	KNXClient.js:835
(anonymous function)           	KNXClient.js:548
onceWrapper                    	events.js:627
emit                           	events.js:525
afterConnect                   	node:net:1263
callbackTrampoline             	async_hooks.js:130
Async call from TCPCONNECTWRAP
init                           	node:in…pector_async_hook:25
emitInitNative                 	async_hooks.js:202
internalConnect                	node:net:1022
defaultTriggerAsyncIdScope     	async_hooks.js:464
(anonymous function)           	node:net:1134
processTicksAndRejections      	task_queues:78
Async call from TickObject
init                           	node:in…pector_async_hook:25
emitInitNative                 	async_hooks.js:202
emitInitScript                 	async_hooks.js:505
nextTick                       	task_queues:133
defaultTriggerAsyncIdScope     	async_hooks.js:464
lookupAndConnect               	node:net:1132
Socket.connect                 	node:net:1101
Connect                        	KNXClient.js:544
(anonymous function)           	knxUltimateModule.js:77
(anonymous function)           	knxUltimateModule.js:15
(anonymous function)           	knxUltimateModule.js:11
Module._compile                	node:in…odules/cjs/loader:1198
Module._extensions..js         	node:in…odules/cjs/loader:1252
Module.load                    	node:in…odules/cjs/loader:1076
Module._load                   	node:in…odules/cjs/loader:911
Module.require                 	node:in…odules/cjs/loader:1100
require                        	helpers:119
(anonymous function)           	main.js:3
Module._compile                	node:in…odules/cjs/loader:1198
Module._extensions..js         	node:in…odules/cjs/loader:1252
Module.load                    	node:in…odules/cjs/loader:1076
Module._load                   	node:in…odules/cjs/loader:911
executeUserEntryPoint          	node:in…/modules/run_main:81
(anonymous function)           	node:in…n/run_main_module:22
```

**Comment by Supergiovane** [comment]
Hi
We’ll take a look asap. 
thanks 🙏

**Comment by Supergiovane** [comment]
Do you use the “secure” knx connection?
What, precisely, have you changed?
Thanks.

**Comment by erdemuncuoglu** [comment]
This is the part that I initialize client:
```
        const client = new KNXClient({
            ipAddr: router.ipAddr,
            ipPort: router.ipPort,
            physAddr: '15.' + (15 - pIndex) + '.' + (254 - rIndex),
            // suppress_ack_ldatareq: false,
            loglevel: config.logLevel,
            // localEchoInTunneling: true,
            hostProtocol: router.secure ? "TunnelTCP" : "TunnelUDP",
            isSecureKNXEnabled: router.secure,
            jKNXSecureKeyring: router.secure ? keyring.default.load(router.keyRing, router.password) : ""
        });
...
        client.Connect();
```
I fill parameters `keyring` and `password` from `secureSample.ts`. I receive same error when my project's export is used.

**Comment by robertsLando** [comment]
@erdemuncuoglu just to know does this used to work before 2.0.0? I never tried with knx secure so it could be a small bug regression introduced after the switch to typescript. 

@Supergiovane I can take a look at this tomorrow

**Comment by erdemuncuoglu** [comment]
I tried with both 2.1.2 and 2.0.0

**Comment by erdemuncuoglu** [comment]
What is the latest version before typescript?

**Comment by erdemuncuoglu** [comment]
I tried with version 1.0.49 and received same error.

**Comment by Supergiovane** [comment]
Guys, knx secure in still under development. Currently it does not work.

**Comment by honestrock** [comment]
@Supergiovane Thank you for the library , Do you have any plans to complete the knx secure development process?

**Comment by Supergiovane** [comment]
Hi,
we're working on the resilience of the Typescript version. @robertsLando did a wonderful job on that. 
Then, we'll take a look at the secure part as well. It's partially done, but i have no release date.
I'm working on the KNX 3rd Party IOT API as well, so we've another layer of compatibility with such new promising (?) protocol.

**Comment by robertsLando** [comment]
I can start working on secure once I find some free time but I don't expect to have many for next couple of weeks at least

**Comment by Supergiovane** [comment]
> @Supergiovane I think that a good way to test it is to use it in the node-red node, maybe you could create a beta version of it and start receiving feedbacks

Do you mean the current KNXUltimate in Typescript version?

**Comment by robertsLando** [comment]
Yeah, add it as a dependency instead of using the local one you ship with the node, this: https://github.com/Supergiovane/node-red-contrib-knx-ultimate/tree/master/KNXEngine

Should be dropped IMO and installed as a dependency instead
