### ISSUE TITLE
NPM build issue v2.1.3

### ISSUE THREAD

**Issue by maulik9898** [Supergiovane/KNXUltimate#22]
**Salutation**
the system will close the issue if you don't even says "Hello", "Hi", or something like this.

**Describe the bug**
When I installed v 2.1.3 of knxultimate from NPM I still get errors like this 

`

      > @enmatter/server@ build /home/lenovo/learning/enmatter/apps/server
      > tsc -p tsconfig.json

      src/plugins/knx/readFromKNX.ts(34,23): error TS2339: Property 'clearToSend' does not exist on type 'KNXClient'.
      src/plugins/knx/sendAllReadRequ
      src/plugins/knx/readFromKNX.ts(34,23): error TS2339: Property 'clearToSend' does not exist on type 'KNXClient'.
      src/plugins/knx/sendAllReadRequ  ✖  nx run @enmatter/server:build
      > @enmatter/server@ build /home/lenovo/learning/enmatter/apps/server
      > tsc -p tsconfig.json

      src/plugins/knx/readFromKNX.ts(34,23): error TS2339: Property 'clearToSend' does not exist on type 'KNXClient'.
      src/plugins/knx/sendAllReadRequests.ts(14,25): error TS2339: Property 'clearToSend' does not exist on type 'KNXClient'.
       ELIFECYCLE  Command failed with exit code 2.

   ✔  nx run web:build (6s)

`

and still get error like DPT9.001 is not valid DPT.

when I download knxultimate 2.1.3 from npm as package using `npm pack knxultimate@2.1.3` I can see that in `buid/dptlib/dpt9.js` has Wrong ID it still DPT2. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Supergiovane** [comment]
Hello.
The issue has been fixed...

<img width="972" alt="Cursor_e_dpt9_ts_—_KNXUltimate" src="https://github.com/Supergiovane/KNXUltimate/assets/37666636/2679e3a0-e453-4cd2-80ca-8e184540a91b">

From where you import knxultimate? From NPM or from gitHub release?

**Comment by maulik9898** [comment]
Fron npm

**Comment by robertsLando** [comment]
@Supergiovane Seems you dind't used the usual release workflow, let me do a new release 2.1.4 and see if that works. I think you forgot to build before doing the manual release (this is automatically handled by release-it when using the automated workflow)

**Comment by robertsLando** [comment]
@maulik9898 Try with 2.1.4

**Comment by maulik9898** [comment]
Its working now

**Comment by Supergiovane** [comment]
> @Supergiovane Seems you dind't used the usual release workflow, let me do a new release 2.1.4 and see if that works. I think you forgot to build before doing the manual release (this is automatically handled by release-it when using the automated workflow)

I've had issues with 2FA authentication, using release-it. Maybe i've missed some steps..
Sorry maulik9898
