### ISSUE TITLE
writeRaw broken with length <= 6bits

### ISSUE THREAD

**Issue by RealByron** [Supergiovane/KNXUltimate#23]
**Salutation**
Hi there, thanks a lot for this wonderful piece of code ;-)

**Describe the bug**
short GroupValueWrite in writeRaw is not sent properly

**To Reproduce**
simply call 
knxUltimateClient.on(KNXClientEvents.connected, info => {
    // The client is connected
    console.log("Connected. On Duty", info);
    // WARNING, THIS WILL WRITE ON YOUR KNX BUS!
    knxUltimateClient.writeRaw("0/1/1", Buffer.from("05", "hex"), 3);
});

**Expected behavior**
should send a effective knx frame ending with value 0x83 , but sends .... 0x80

**Screenshots**

**Desktop (please complete the following information):**
 - OS: node

**Additional context**
A PR with the missing Math.ceil function to come now !!

**Comment by Supergiovane** [comment]
Thanks. I'll wait for the PR!
