### ISSUE TITLE
DPT 9.001 seems to round values erratically

### ISSUE THREAD

**Issue by Supergiovane** [Supergiovane/KNXUltimate#32]
**Salutation**
Hi, nice to meet you.

**Describe the bug**
Please see here: #https://github.com/Supergiovane/node-red-contrib-knx-ultimate/issues/377

**To Reproduce**
Read the issue in the link above

**Expected behavior**
DPT 9.001 rounding correctly

@robertsLando can you check this issue please? It's on knx-utlmate for node-red, but it's related to this package here.

**Comment by robertsLando** [comment]
I think the problem is you are using `toFixed to round it:

https://github.com/Supergiovane/KNXUltimate/blob/86bb2c9004eac891ec7dac9dc26733b41e4edd67/src/dptlib/dpt9.ts#L21
