### ISSUE TITLE
IP Tunneling with NAT

### ISSUE THREAD

**Issue by Lzolcsi** [Supergiovane/KNXUltimate#6]
Hi!

I'd like to connect to an IP tunneling device, that is behind a router. Port forwarding is set up correctly, I can connect with ETS just fine (by ticking the NAT checkbox), but KNXUltimate gives a timeout error almost immediately. I'm assuming, that NAT is not supported at the moment. Would it be possible, to make this work somehow?

Thanks!

**Comment by Supergiovane** [comment]
Hi
I’m currently on holidays. I’ll take a look next week.

**Comment by Lzolcsi** [comment]
Have a good time, cheers! :)

**Comment by Lzolcsi** [comment]
FYI, I found a JAVA lib, that supports NAT, maybe that could be of some help.
https://github.com/pitschr/knx-core

**Comment by Supergiovane** [comment]
Thank you!
I had enabled NAT in the past, but many misuses and complaints of users unaware of when to use NAT or when not to use it, had me convinced to remove it. 
You are the first one asked me about enabling  NAT. You understand what you're doing..great!
I'm happy to rebuild the HPAI packet with the route back functionality. Please allow me enjoying this vacation's week. I'll dive into it next week.

**Comment by Supergiovane** [comment]
Hi,
in the meantime, you could try to pass your local IP address, via . **localIPAddress**, and pass the ehernet interface's name as well, via . **KNXEthInterface**.

Like this:

```

// Set the properties
let knxUltimateClientProperties = {
    localIPAddress: "192.168.1.201",    
    KNXEthInterface: "eth1"
};

```

I don't remember if it enables the NAT or not, but next week i'll take a look anyway.

**Comment by Supergiovane** [comment]
Hi, 
could you try, please to unzip this file into the KNXUltimate folder?
[src.zip](https://github.com/Supergiovane/KNXUltimate/files/11897481/src.zip)


Then, by setting knxUltimateClientProperties.localSocketAddress={address:'x.x.x.x' , port:yyyy}, you should be able to natting the packets. At least the connect request packet.
Leaving localSocketAddress undefined, it should work as usual.

If you are in trouble, just download the official knxultimate again.

**Comment by Lzolcsi** [comment]
Thanks for the effort, so far I can't get it to work. But please enjoy the rest of your holiday, and don't worry about this... :)

**Comment by Supergiovane** [comment]
Hmmm... i need to set a test bed, once at home.

Is this your setup?
You ---> | WAN |--->KNX/IP interface

**Comment by Lzolcsi** [comment]
yep, something like that.
Server (running knxUltimate) -> WAN -> KNX/IP interface.
I can give you access to my KNX installation once you get back for testing purposes (in private). But seriously though, disregard my email for the week and do enjoy your vacation! :)

**Comment by Supergiovane** [comment]
Hi
you know... i'm on the beach doing nothing. So i must do something.
I've tried with the connection from here, via LTE, to my KNX/IP at home.

<img width="896" alt="UniFi_Network_-_UDM_SE" src="https://github.com/Supergiovane/KNXUltimate/assets/37666636/8d2e0cc1-26a2-4909-be70-a3f537229124">

The telegrams are flowing without issues.

https://github.com/Supergiovane/KNXUltimate/assets/37666636/9a5404a7-64e7-4bca-9b63-9de158cee09b


I'm here on the beach, with my mac using node-red, tethered with my iPhone.
I'm connecting to my home where i've set up a port forwarding to my KNX/IP interface.

Can you enable set the log to DEBUG, and share the results here?

**Comment by Lzolcsi** [comment]
I can relate to that... :)

port forwarding looks fine to me, I tested the connection with ETS from my cellular network. But here is a pic of it:
<img width="1428" alt="Screenshot 2023-06-29 at 15 56 08" src="https://github.com/Supergiovane/KNXUltimate/assets/3718245/ee2074f2-6472-4808-92d7-d16d21e4e035">
I think I might use the configuration params incorrectly, this is what I tried:

```
let conn = new knx.KNXClient({
            ipAddr: 'XXX', //IP of my WAN interface
            ipPort: 3671,
            physAddr: '1.1.1',
            suppress_ack_ldatareq: false,
            loglevel: "error", // or "debug" is the default
            localEchoInTunneling: true, // Leave true, forever.
            hostProtocol: "TunnelUDP", // "Multicast" in case you use a KNX/IP Router, "TunnelUDP" in case of KNX/IP Interface, "TunnelTCP" in case of secure KNX/IP Interface (not yet implemented)
            isSecureKNXEnabled: false, // Leave "false" until KNX-Secure has been released
            jKNXSecureKeyring: "", // ETS Keyring JSON file (leave blank until KNX-Secure has been released)
            localIPAddress: 'xxxxxxx', //IP of the server where the code is running
            localSocketAddress: {
                address: 'xxxxxxx', //tried both IP here
                port: 3671
            },
            KNXEthInterface: "eth0", // Bind to the first avaiable local interfavce. "Manual" if you wish to specify the interface (for example eth1); in this case, set the property interface to the interface name (interface:"eth1")
        });
```

could you possibly post a screenshot of your configuration (with the IP addresses changed to descriptive lines)?

Thanks

**Comment by Supergiovane** [comment]
Hi
It is basically the same config as yours. 
Do you have a public ip address at home? I mean… do you have double nat, i.e your Unifi Gateway is behind another router, or the Unifi Gateway has its own public IP?

Can you please install knxultimate from npmjs again and try again, striping down the config like this?

```
let conn = new knx.KNXClient({
            ipAddr: 'XXX', //IP of my WAN interface
            ipPort: 3671,
            physAddr: '1.1.1',
            suppress_ack_ldatareq: false,
            loglevel: "error", // or "debug" is the default
            localEchoInTunneling: true, // Leave true, forever.
            hostProtocol: "TunnelUDP", // "Multicast" in case you use a KNX/IP Router, "TunnelUDP" in case of KNX/IP Interface, "TunnelTCP" in case of secure KNX/IP Interface (not yet implemented)
            isSecureKNXEnabled: false, // Leave "false" until KNX-Secure has been released
            jKNXSecureKeyring: "", // ETS Keyring JSON file (leave blank until KNX-Secure has been released)
            KNXEthInterface: "eth0", // Bind to the first avaiable local interfavce. "Manual" if you wish to specify the interface (for example eth1); in this case, set the property interface to the interface name (interface:"eth1")
        });
        

```

If unsuccessful, you can try using the multicast protocol and the knx standard multicast IP, provided your knx gateway is a router as well. 
If unsuccesfull, please wait until i’m at home. I’ll connect briefly to your knx gateway for testing…

**Comment by Lzolcsi** [comment]
Nope, still nothing. I have a public IP, I'm not NAT-ed. I think multicast wouldn't work, my device does only have an IP interface, no routing capabilities.

**Comment by Supergiovane** [comment]
Hi
have you tried striping down your config parameters, like shown in my screenshot?
You could try to change the WAN port, from 3671 to, for example 51000.

**Comment by Supergiovane** [comment]
Please send me your public IP address here maxsupergiovane@icloud.com
I'll try from the beach.

**Comment by Supergiovane** [comment]
Hi again
i cannot even ping your WAN.
Are you sure, you don't have any GEO-IP blocking on your Unifi Gateway? Where are you from?

**Comment by Supergiovane** [comment]
You have definately some firewall filter. I've tried connecting from Italy and Germany, pinging your WAN IP and doing a port scan, but the connection times out every time.

**Comment by Lzolcsi** [comment]
You are right, something must be going on with this, I'll try to figure it out. Thanks for the help! I'll get back to you with the results.

**Comment by Supergiovane** [comment]
Hi
tried with port 51000 again, without success.
I cannot even ping your WAN IP.

**Comment by Lzolcsi** [comment]
Can you try port 5100 please?

**Comment by Supergiovane** [comment]
Tried now, but nothing. Timeout. Like with the ping.

**Comment by Lzolcsi** [comment]
Thanks, I'll try figuring it out. I think ping is disabled, but still, KNX should work, ETS connects just fine on port 5100 through my cellular network. But ping is not working for me from my cell as well, so I think it is disabled. 
It definitely looks like some sort of geo-blocking, I can telnet to 5100 just fine from my cell and from a hungarian server, but not from DigitalOcean. I'll try to figure it out, and get back to you once it's done.
Thanks again for the help!

**Comment by Lzolcsi** [comment]
OK, I see some strange things here:

This tests to see if I can connect to my KNX installation via UDP.
nc -z -v -u WAN_IP 5100 
This succeeds from both the Hungarian and the German server


This tests to see if I can connect to my KNX installation via TCP.
nc -z -v -u WAN_IP 5100 
This succeeds only from the Hungarian server. 
So one strange thing is that no firewall rules are set in Unifi for these, so both of them should work. Also, KNX should only use UDP, so it shouldn't even matter.

**Comment by Supergiovane** [comment]
Hi
Please try to connect to my home. 
2.44.100.198 Port 51000
Please, if you need,  switch only the group address 4/4/4
Thanks.

**Comment by Lzolcsi** [comment]
Oh my god....
I did not use .Connect(), it was left out in the big copy-and-pasting job.....

So this is where I am now:
It works fine from the Hungarian server (vanilla code, no extra settings). It doesn't work from DigitalOcean. Seems like something happens to TCP packets that come from a different country. Maybe my ISP is doing something, or maybe it's DigitalOcean, I honestly don't know what's happening, but I think I'll just stick to installing it on a Hungarian server.

Thanks so much for bearing with me through this, I can finally get to the real work now :)
And thanks for your work!
Have a nice holiday (at least what's left of it) :)

**Comment by Supergiovane** [comment]
Thank you! Now it’s shopping time (not mine, my wife).
