### ISSUE TITLE
Reconnection errors

### ISSUE THREAD

**Issue by elausys** [Supergiovane/KNXUltimate#7]
Hello,

First of all, thank you and congratulation for the great KNX library !

I'm facing an issue to reconnect after loosing the connection to the KNX IP Interface in tunnel mode. If I disconnect the KNX Gateway from the network, the status of the Client changes to disconnected but after plugging back the Gateway to the network and calling the KNXUltimateClient.Connect() function again, i keep getting the following errors :

```
[error] 1/12/2024, 3:37:41 PM.847 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

[error] 1/12/2024, 3:37:47 PM.168 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
```

Log file : 
[log.txt](https://github.com/Supergiovane/KNXUltimate/files/13920942/log.txt)

I would really appreciate your support to solve this problem.

Thanks a lot,
Nicolas

**Comment by Supergiovane** [comment]
Hi
I’m on holiday now and cannot check. Please try to close the connection first with KNXUltimateClient.close() or KNXUltimateClient.disconnect (). 
I cannot recall yet the right one. The reconnection shouldn’t really an issue for the library. 
Or try to setup again the connection from scratch, by instantiating the lobrary with another “new” call.

**Comment by Supergiovane** [comment]
Hi
have you tried to close and disconnect?

**Comment by Supergiovane** [comment]
Thanks.

**Comment by Supergiovane** [comment]
Hi
Here https://github.com/Supergiovane/node-red-contrib-knx-ultimate/blob/master/nodes/knxUltimate-config.js there is a fully working code.
What it does, is to call .Disconnect(), then instantiate again the connection with `node.knxConnection = new knx.KNXClient(node.knxConnectionProperties);` where node.knxConnectionProperties contains all the parameters to pass to the KNXClient.

**Comment by elausys** [comment]
Hi,

I'm basically doing the same logic, you see attached the source code of the two functions that handles the connection.
checkAndTryConnectWithKnx checks the connection state and repeat the connect by calling the function initKNXConnection.

[source.txt](https://github.com/Supergiovane/KNXUltimate/files/13998236/source.txt)

I attach the complete log here as well.
[server-out.log](https://github.com/Supergiovane/KNXUltimate/files/13998240/server-out.log)

I performed a few connect/disconnect and logged the results.
See below the times and lines in the log where the events occur.
After each new connection, the connection is established, but all previous instances keep of creating errors.
I have also tried to set KNXUltimateClient = null before creating a new instance without succes.

See below the details :

1) Disconnect : 9:48 (Line 199)

2 ) Connect : 9:52 (Line 340) 

Connection is etablished but the previous instance keeps sending errors :

Error at 9:54 at line 4707 (KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running)

[error] 1/20/2024, 9:54:40 AM.794 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 1
KNX Error Error: Connection dead with 192.168.1.57:3671
******************   KNX Disconnected 192.168.1.57:3671 Connection dead with 192.168.1.57:3671

3) Disconnect : 9:57 at line 4818

4) Connect : 10:01 at line 5000

Connection is etablished but the two previous instances keeps sending errors :

[error] 1/20/2024, 10:03:21 AM.219 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

[error] 1/20/2024, 10:03:30 AM.864 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

[error] 1/20/2024, 10:03:31 AM.219 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 1
KNX Error Error: Connection dead with 192.168.1.57:3671

******************   KNX Disconnected 192.168.1.57:3671 Connection dead with 192.168.1.57:3671
[error] 1/20/2024, 10:03:40 AM.862 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 1


5) Disconnect : 10:07 at line 9705

6) Connect : 10:12 at line 10075

Connection is etablished but the three previous instances keeps sending errors :

[error] 1/20/2024, 10:14:21 AM.238 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

[error] 1/20/2024, 10:14:21 AM.289 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

[error] 1/20/2024, 10:14:30 AM.950 KNXUltimate-KNXEngine: Sending KNX packet: Send UDP Catch error: Not running object seqCounter:undefined
KNX Error Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running

[error] 1/20/2024, 10:14:31 AM.237 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 1
KNX Error Error: Connection dead with 192.168.1.57:3671

[error] 1/20/2024, 10:14:31 AM.288 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 1
KNX Error Error: Connection dead with 192.168.1.57:3671

[error] 1/20/2024, 10:14:40 AM.949 KNXUltimate-KNXEngine: KNXClient: getConnectionStatus Timeout 0 out of 1
KNX Error Error: Connection dead with 192.168.1.57:3671


Thank you in advance for your support.

Best Regards,

**Comment by Supergiovane** [comment]
I’ll return to office monday, but in the meantime, i saw this:

```
knxUltimateClient.Disconnect();
                initKNXConnection(true, true);

```

.Disconnect is async
You sbould call the initKNXConnection in the “disconnect” event, not directly below the .disconnect() command.

**Comment by elausys** [comment]
Hi,

Actually the logs i sent before was without the Disconnect();

When i add the Disconnect() before the initKNXConnection, there is an additional event that says it is already disconnected :

`knxUltimateClient Connect Error Error: KNX Socket is already disconnected
    at KNXClient.Disconnect (/projects/hv_server/server/utils/knx/KNXClient.cjs:656:13)
    at Timeout.checkAndTryConnectWithKnx [as _onTimeout] (file:///projects/hv_server/server/utils/socketio/index.js:607:35)`

And then it does not reconnect.

See complete log attached.
[log (2).txt](https://github.com/Supergiovane/KNXUltimate/files/14039320/log.2.txt)

**Comment by Supergiovane** [comment]
Hi
have you tried to put the initKNXConnection, into the "disconnected" event?
You also need to remove all listeners you created, prior to instantiating a new instance, using the command **KNXClient..removeAllListeners()**;
The code i pointed you out to, is something like this:

```
KNXClient.removeAllListeners();
KNXClient = new knx.KNXClient({...JSONobject with the connection properties});
KNXClient.on(knx.KNXClient.KNXClientEvents.disconnected, (info) => {
    if (KNXClient !== null) KNXClient.Disconnect();
 });

```

When calling .Disconnect(), all timers, watchdog and probes are stopped and destroyed.

**Comment by elausys** [comment]
Hi,

Yes, I added both now and previous instances continue to send these errors : 
 
![image](https://github.com/Supergiovane/KNXUltimate/assets/152511534/01a928c4-d7c2-48d8-a239-00936eb8e9e7)

**Comment by elausys** [comment]
Hi, anything else I should check to fix this issue ? Thanks

**Comment by Supergiovane** [comment]
Hi
There should be something in you code, not allowing the instance to be nullified. 
You could try to downloadthe latest knxultimate version, but you should revise your code. I cannot help muchfrom here.

**Comment by Supergiovane** [comment]
Hi
have you solved the issue?

**Comment by Supergiovane** [comment]
If you wish, i can take a look at your code...

**Comment by Supergiovane** [comment]
Let me see your code. I may be able to help you.

**Comment by elausys** [comment]
Sure, thanks a lot. Tomorrow I can provide you a remote access in private so you can view the code.

**Comment by elausys** [comment]
Hi,

Can we plan to do this ? Thanks a lot

**Comment by Supergiovane** [comment]
Hi
I'm out of home!! We can try Monday!

**Comment by elausys** [comment]
OK, thank you, let me know when you are available.

**Comment by elausys** [comment]
Hi, 
Are you still willing to take a look at the code ? 
When would you be available ? 
Thanks a lot

**Comment by Supergiovane** [comment]
Ops... Sorry, i forgot that.
Can i access your code now?

**Comment by elausys** [comment]
Hi,
You can connect on AnyDesk 689892438

**Comment by Supergiovane** [comment]
I'm downloading anydesk...

**Comment by elausys** [comment]
sorry i don't know whats going on with the keyboard. If you want i can reboot.

**Comment by Supergiovane** [comment]
Hi,
have you had issues again?
I can connect to you, at about **14.30.**' o clock.
 I will use again the anydesk number 689892438

**Comment by elausys** [comment]
i did not make any disconnect because it already shows some errors after startup, so you can see it first.
OK perfect.

**Comment by Supergiovane** [comment]
Hi,
I'm ready.
