### ISSUE TITLE
KNX Scene recall

### ISSUE THREAD

**Issue by gtnscebba** [Supergiovane/KNXUltimate#9]
Hi Massimo,
in the past, with your KNXUltimate I was able to recall a specific KNX scenario.

Now, with some upgrade version (I don't know what), the flow doesn't operate anymore.

My flow is:
1) with a function I set msg.payload = { "save_recall": 0, "scenenumber": 2 }      // 2 = Notte
2) the following KNXDevice uses group addess 4/0/0 with a Datapoint 18.001
3) the flag "React to write telegrams" is set 

Obviously the same behaviour is for all other scenarious.

How can I solve?

Regards

**Comment by Supergiovane** [comment]
Hi Gaetano
Can i see the KNXDevice 4/0/0 config window?

**Comment by Supergiovane** [comment]
Ops... sorry! I tough it was node-red!
Please disregard my request

**Comment by Supergiovane** [comment]
Can i see your piece of node.js code?

**Comment by gtnscebba** [comment]
![image](https://github.com/Supergiovane/KNXUltimate/assets/127748194/e66d800a-bdcc-4aed-a266-da45c48add23)

**Comment by gtnscebba** [comment]
If the scenarious are executed by physical buttons run correctly.

**Comment by Supergiovane** [comment]
Ok, so you are on node-red :-)
That node is very old.
Can you please copy it and paste the code here? I need to test with your old node.

**Comment by gtnscebba** [comment]
![image](https://github.com/Supergiovane/KNXUltimate/assets/127748194/6657c2c2-4e45-4e80-982a-bebde6014e0d)

The function content is:
msg.payload = { "save_recall": 0, "scenenumber": 2 }

return msg;

**Comment by Supergiovane** [comment]
Hi Gaetano
please change it to **msg.payload = {save_recall:0, scenenumber:2}** (without double quotes) and try again

**Comment by gtnscebba** [comment]
Massimo,
it works. 

Thanks a lot, ciao!

**Comment by Supergiovane** [comment]
Bye.
